repos:
- repo: https://github.com/norwoodj/helm-docs
  rev: v1.2.0
  hooks:
  - id: helm-docs
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: charts/.*/README.md
  - id: check-yaml
    exclude: charts/.*/templates/
  - id: check-added-large-files
