{{- if .Values.sealedSecrets -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "fider.fullname" . }}
  labels:
    {{- include "fider.labels" . | nindent 4 }}
spec:
  encryptedData:
    DATABASE_URL: {{ required "fider.databaseUrl is required" .Values.fider.databaseUrl }}
    JWT_SECRET: {{ required "fider.jwtSecret is required" .Values.fider.jwtSecret }}
    {{- if .Values.fider.smtp }}
    EMAIL_SMTP_PASSWORD: {{ .Values.fider.smtp.password | default "" }}
    {{- end }}
    {{- if .Values.fider.mailgun }}
    EMAIL_MAILGUN_API: {{ .Values.fider.mailgun.api }}
    {{- end }}
{{ toYaml .Values.extraEnvSecrets | indent 4 }}
{{- else -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fider.fullname" . }}
  labels:
    {{- include "fider.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ required "fider.databaseUrl is required" .Values.fider.databaseUrl }}
  JWT_SECRET: {{ required "fider.jwtSecret is required" .Values.fider.jwtSecret }}
  {{- if .Values.fider.smtp }}
  {{- if .Values.fider.smtp.password }}
  EMAIL_SMTP_PASSWORD: {{ .Values.fider.smtp.password }}
  {{- end }}
  {{- end }}
  {{- if .Values.fider.mailgun }}
  EMAIL_MAILGUN_API: {{ .Values.fider.mailgun.api }}
  {{- end }}
  {{- if .Values.fider.facebook }}
  OAUTH_FACEBOOK_SECRET: {{ .Values.fider.facebook.secret }}
  {{- end }}
  {{- if .Values.fider.google }}
  OAUTH_GOOGLE_SECRET: {{ .Values.fider.google.secret }}
  {{- end }}
  {{- if .Values.fider.github }}
  OAUTH_GITHUB_SECRET: {{ .Values.fider.github.secret }}
  {{- end }}
{{- if .Values.extraEnvSecrets }}
{{ toYaml .Values.extraEnvSecrets | indent 2 }}
{{- end }}
{{- end -}}
